### PR TITLE
A few additions and corrections

### PR DESCRIPTION
**Pull request by nlenkowski**
This is a nice list, we should definitely publish it. When I have some free time I'm going to whip up a quick design.

### CODE REVIEW

**Comment by nlenkowski** [comment]
Any chance of getting this year old pull request merged? ;-)

**Comment by jpetto** [comment]
I'm so mad at you for calling attention to my lack of attention on this project. How dare you embarrass me like that? :trollface:

**Comment by jpetto** [comment]
Care to [squash your commits](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/)?

**Comment by nlenkowski** [comment]
Commits squashed, all good?

**Comment by nlenkowski** [comment]
Squashing newbie here. I squashed the three commits into one, but forgot to set the -f flag during the push, hence the wonky "Merge branch" commit. Or so I think. Going to close this pull request, try and do it right and reopen.

**Pull request closed without merging**
